import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/Layout'
import { AuthProvider } from '../components/auth/AuthProvider';
import { useState, useEffect, useContext  } from 'react';


function MyApp({ Component, pageProps }) {
  const [showSplash, setShowSplash] = useState(true);
useEffect(() => {
  const timeout = setTimeout(() => {
    setShowSplash(false);
  }, 1500);

  return () => clearTimeout(timeout);
}, []);

  return (
    <>
    {showSplash && (
  <div className="splash-screen">
    {/* Acá le podés poner una imagen si querés */}
   <img src="/img/stern.png" alt="Logo" className="splash-image"/>
  </div>
)}
     <Head>
      <title>LZ-Ninja</title>
      <meta charSet="UTF-8"></meta>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/img/logo-lager.png" />
       {/* <link rel="icon" href="/img/ninja-face-white.png" /> */}
       {/* <link rel="icon" href="/img/stern.png" /> */}
    </Head>

       <AuthProvider>
        <Layout >
            <Component {...pageProps} />
            
        </Layout>
      </AuthProvider>
      <style jsx>{`
.splash-screen {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(178, 223, 255, 1);
  z-index: 9999;
  display: flex;
  justify-content: center;
  align-items: center;
  animation: slideOut 0.5s ease-out forwards;
  animation-delay: 1.2s;
}

.splash-image {
  max-width: 250px;
  max-height: 250px;
  object-fit: contain;
    animation: spin 5s linear infinite;
        }
        @keyframes spin {
          from {
            transform: rotate(0deg);
          }
          to {
            transform: rotate(360deg);
          }
        }

@keyframes slideOut {
  0% {
    transform: translateX(0%);
  }
  100% {
    transform: translateX(-100%);
  }
}



          @media (max-width: 768px) {
            .splash-image {
            max-width: 250px;
            max-height: 250px;
            object-fit: contain;
              animation: spin 2s linear infinite;
        }
        @keyframes spin {
          from {
            transform: rotate(0deg);
          }
          to {
            transform: rotate(360deg);
          }
        }
      
  }

  @media (max-width: 480px) { 

    }

      `}
      </style>

    </>
  )
}

export default MyApp
