import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/Layout'
import { AuthProvider } from '../components/auth/AuthProvider';
import { useState, useEffect, useContext  } from 'react';


function MyApp({ Component, pageProps }) {
  const [showSplash, setShowSplash] = useState(true);
useEffect(() => {
  const timeout = setTimeout(() => {
    setShowSplash(false);
  }, 1500);

  return () => clearTimeout(timeout);
}, []);

  return (
    <>
    
     <Head>
      <title>LZ-Ninja</title>
      <meta charSet="UTF-8"></meta>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/img/logo-lager.png" />
       {/* <link rel="icon" href="/img/ninja-face-white.png" /> */}
       {/* <link rel="icon" href="/img/stern.png" /> */}
    </Head>

       <AuthProvider>
        <Layout >
            <Component {...pageProps} />
            
        </Layout>
      </AuthProvider>
      <style jsx>{`


          @media (max-width: 768px) {
      
  }

  @media (max-width: 480px) { 

    }

      `}
      </style>

    </>
  )
}

export default MyApp
